### PR TITLE
Bio-Fuel rework [WIP]

### PR DESCRIPTION
**Pull request by DrParadox7**
This is a WIP commit for reworking the Mekanism module on Plastics and BioFuel.

The scope of the commit is to get these processes reworked to be closer to reality and more balanced.
-Biofuel is Ethylene IRL, which involves fermentation with yeast.
-Ethene is concentrated Ethylene.

As of current, Bio-Generators are uninteresting and weak for they can make energy with no setup:
Pulverize organic matter (wheat, apple, zombie flesh, etc...) -> Energy!

The new envisioned process follows the following steps:
1) Biomatter from pulverized organics _[Present in base Mekanism]_
image

2) Oxidize Biomatter into gas [New]
image

3) Make Yeast [New]
image

_Yeast Duplication:_
image

4) Ethylene and Substrate [New]
(from Steam + Yeast + Biomatter Gas)
image

5) Ethene from Ethylene for a further kick in Energy generation:
image

The Bio-Generator would be converted into accepting gases rather than items.

This new iteration would accept 2 gases:
-Biomatter Gas _(Early-game)_
-Ethylene _(Mid-game)_

**To Do:**
- [x] Add initial resources
- [x] Add initial recipes
- [x] Convert Bio-Generator to gas based fuel
- [x] Finalize numbers on recipes and output of Bio-Generator

### CODE REVIEW

**Comment by maggi373** [comment]
maybe rename metalurgic infuser aswell?

**Comment by DrParadox7** [comment]
It always had non metallic infusions. 
For something that has been labeled as such for a near decade it is better to leave it at that to avoid confusion.

**Comment by maggi373** [comment]
Was just thinking of removing metallurgic from the name....

**Comment by DrParadox7** [comment]
@maggi373 This is finished now. You can test it out and see what you think.
I'd love some feedback on it

**Comment by DrParadox7** [comment]
It also fixes a bug with the Gas Generator not accepting gases when empty.

**Review by maggi373 — APPROVED** [review]

**Comment by 167OSS** [comment]
Is it possible to add a configuration option to make ethene available as before?

**Comment by maggi373** [comment]
> Is it possible to add a configuration option to make ethene available as before?

@167OSS please make an enhancement request, this is a three year old pr.

**Pull request merged**
