### PR TITLE
Added Protected Frequencies to Teleporter and QuantumEntangloporter

### PR DESCRIPTION
**Pull request by Pokemonplatin**

### CODE REVIEW

**Comment by maggi373** [comment]
any specific reason for downgrade for gradle and forge? just wondering. But i see that you use eclipse so we probably need to add gitignore on idea and eclipse stuff in gradle. But it compiled fine :)

**Comment by maggi373** [comment]
Got the client running after i found out that you get 404 on chickenbones maven when downloading dependencies

**Comment by Pokemonplatin** [comment]
> any specific reason for downgrade for gradle and forge? just wondering. But i see that you use eclipse so we probably need to add gitignore on idea and eclipse stuff in gradle. But it compiled fine :)

I actually use InteliJ and i downgraded gradle because i had problems setting the project up and it worked fine with that version.
My dev environment for mekanism is a cluster fuck as it breaks when intelij trys to load the gradle as its too old. So i have to compile it using commandline and import the whole project as an eclipse project.

Oh and the forge downgrade was an oversight on my part

**Comment by maggi373** [comment]
Well its weird that gradle 3 dont work, will look on it soon

**Comment by maggi373** [comment]
6 months ago i got mekanism working with gradle 3.0 and idea fine but it does not work anymore. So im going to see if i can get it to work again.

**Comment by maggi373** [comment]
my laptop works fine with gradle 3 so im using github actions to fix it

**Comment by maggi373** [comment]
should be fixed now

**Pull request merged**
