### PR TITLE
fix fluidtank duplication with fluidstacks Thorfusion#49

### LINKED ISSUE #49: [BUG] Drum duplication trough tanks
**Duplication on fluid tanks**
when filling a fluid tank with any liquid and adding stacked drums (Extra Utilities) in the fluid tank slot, the liquid present in the fluid tank fills all drum

**To Reproduce**
1. place any fluid tank and fill then whith any liquid
2. open the fluid tank and insert a stack of Drum (Extra Utilities)
3. Change mode of Fluid tank to Fill

**Expected behavior**

**Screenshots**

Screenshot_5
Screenshot_6
Screenshot_7

**Desktop (please complete the following information):**
 - OS: Win 10
 - Modpack: Custom
 - Modpack Version: Custom
 - Mekanism Version: Latast version

**Please provide the following files**
+ The crash report in folder ./crash-reports (both server and client logs)
+ The full log located in the folder ./logs
+ The configfiles in ./config/mekanism/
+ In special cases where there will be alot of work, also provide the save file where the error occurs.
Use gist.github.com to provide such files.

**Additional context**

### PR DESCRIPTION
**Pull request by maggi373**

### CODE REVIEW

**Review by DrParadox7 — COMMENTED** [review]
Commit erroneously marked as issue #52. 
This is #49.

**Comment by maggi373** [comment]
Tried to edit the commit yesterday, just made shit worse

**Comment by DrParadox7** [comment]
The Dynamic Tank was missed here.
Does it not have the same issue?

**Comment by DrParadox7** [comment]
The following tiles share this issue:
-Dynamic Tank
-Electric Pump
-Thermal Evaporation Controller
-Boiler
-Rotary Condensentrator

The method implemented works reliably tho

**Comment by maggi373** [comment]
ye, they also have the issue, my bad for not checking

**Review by DrParadox7 — APPROVED** [review]
All fixes tested and working.

**Pull request merged**
