### PR TITLE
Clean Up Integration Modules

### PR DESCRIPTION
**Pull request by DrParadox7**
Merged and refactored `OreDictOsmium` and `OreDictPlatinum` under `PlatReplacement`. 
Cleaned up BoP and Silicon module.

### CODE REVIEW

**Comment by maggi373** [comment]
can you make it so it supports pack that uses both oredicts?

**Comment by DrParadox7** [comment]
Having both Osmium and Platinum as output messes up the ore processing.
What kind of compat do you have in mind?

**Comment by maggi373** [comment]
currently the silicon module is missing one of its oredicts. thats an issue need fixing

**Comment by maggi373** [comment]
for the platinum thingy, i just want to be able to use osmium in platinum recipes and platinum in osmium recipes. as minetweaker cant do the job, we have to bake it in. but its a time ago i added this and cant remember all the details, all i know its crucial to have for some of the factories on my server.

**Comment by maggi373** [comment]
good catch with the bop integration tho

**Comment by DrParadox7** [comment]
> for the platinum thingy, i just want to be able to use osmium in platinum recipes and platinum in osmium recipes. as minetweaker cant do the job, we have to bake it in. but its a time ago i added this and cant remember all the details, all i know its crucial to have for some of the factories on my server.

Minetweaker can do that very easily. Here:
```
<ore:ingotOsmium>.addAll(<ore:ingotPlatinum>); 
<ore:ingotPlatinum>.mirror(<ore:ingotOsmium>);
```
What it can't do is change the recipes

**Comment by DrParadox7** [comment]
Minetweaker Script of the 2 compat as discussed:
https://pastebin.com/D6n65XJv

**Review by maggi373 — APPROVED** [review]

**Pull request merged**
