### PR TITLE
Patch Personal Chest dupe

### PR DESCRIPTION
**Pull request by DrParadox7**
Patches the Personal Chest dupe and adds a fail-safe config for modpacks to prevent the interaction all together.

### CODE REVIEW

**Comment by DrParadox7** [comment]
The way I have tackled this is by closing the GUI when the player switches slots after opening a Personal Chest.

**Comment by maggi373** [comment]
> The way I have tackled this is by closing the GUI when the player switches slots after opening a Personal Chest.

wont fix it but will make it harder, but still that bruh moment when i read that it does not close it atm.

**Comment by DrParadox7** [comment]
> wont fix it but will make it harder

How exactly would you go around that?

**Comment by maggi373** [comment]
> > wont fix it but will make it harder
> 
> How exactly would you go around that?

sorry mate, didnt check the commits, only saw what u wrote

**Comment by DrParadox7** [comment]
When you try to use a chest it will remember from which slot it was opened from.
From there on, the GUI will track your current active slot and should it ever be different than the initial slot it will close.

**Review by maggi373 — APPROVED** [review]

**Comment by maggi373** [comment]
fixes https://github.com/Thorfusion/Mekanism-Community-Edition/issues/130

**Pull request merged**
